---
- name: test
  hosts: webservers
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_user: Administrator
    ansible_password: JustM300
    service_name: IIS Admin Service   
  tasks:
    - name: test whoami
      win_whoami:

