- hosts: localhost
  vars:
    - github_token: "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"
    - ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: Create a GitHub Repo
      github_repo:
        github_auth_key: "{{github_token}}"
        username: "christinilsen"
        name: "Hello-World"
        description: "First repo created with custom Ansible module"
        private: yes
        has_issues: no
        has_wiki: no
        has_downloads: no
        state: present
      register: result