- hosts: localhost
  vars:
    - github_token: "YOUR TOKEN HERE"
    - ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: Create a github Repo
          github_repo:
            github_auth_key: "..."
            username: "YOUR GITHUB USERNAME HERE"
            name: "Hello-World"
            description: "This is your first repository"
            private: yes
            has_issues: no
            has_wiki: no
            has_downloads: no
            state: present
          register: result