- hosts: localhost
  vars:
    - github_token: "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"
    - ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: CreateRepo
      gh_repo:
        github_auth_key:  "{{github_token}}" 
        username: "christinilsen"
        name: "Hello-World"
        description: "First repo created with custom Ansible module"
        private: yes
        has_issues: no
        has_wiki: no
        has_downloads: no
        state: present
      register: result